<?php

namespace Database\Seeders;

use App\Models\PoiType;
use Illuminate\Database\Seeder;

class PoiTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = $this->getPoiTypeDefinitions();

        foreach ($types as $type) {
            PoiType::updateOrCreate(
                ['id' => $type['id']],
                $type
            );
        }
    }

    /**
     * Get all POI type definitions.
     */
    private function getPoiTypeDefinitions(): array
    {
        return [
            // ============================================================
            // STELLAR OBJECTS (Universe domain)
            // ============================================================
            [
                'id' => 17,
                'code' => 'STAR',
                'label' => 'Star',
                'description' => 'A massive luminous sphere of plasma held together by gravity. The central body of a solar system that provides light, heat, and energy. Stars can be harvested for rare fusion materials and exotic particles.',
                'domain' => 'Universe',
                'category' => 'star',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => false,
                'is_dockable' => false,
                'can_have_trading_hub' => true,
                'can_have_warp_gate' => true,
                'base_danger_level' => 3,
                'icon' => 'star',
                'color' => '#FFD700',
                'produces_minerals' => ['T', 'CP', 'QF', 'SCF'],
            ],
            [
                'id' => 4,
                'code' => 'BLACK_HOLE',
                'label' => 'Black Hole',
                'description' => 'A region of spacetime where gravity is so strong that nothing can escape. Extremely dangerous but contains ultra-rare exotic materials near its event horizon.',
                'domain' => 'Universe',
                'category' => 'anomaly',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => false,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 10,
                'icon' => 'black-hole',
                'color' => '#1a0033',
                'produces_minerals' => ['Nt', 'EM', 'QF', 'CP', 'SCF', 'ZPE', 'PE'],
            ],
            [
                'id' => 19,
                'code' => 'SUPER_MASSIVE_BLACK_HOLE',
                'label' => 'Supermassive Black Hole',
                'description' => 'A black hole with a mass millions to billions times that of the Sun. Found at the center of galaxies. Contains the rarest materials in the universe.',
                'domain' => 'Universe',
                'category' => 'anomaly',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => false,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 10,
                'icon' => 'supermassive-black-hole',
                'color' => '#0d001a',
                'produces_minerals' => ['Nt', 'EM', 'QF', 'CP', 'SCF', 'ZPE', 'PE'],
            ],
            [
                'id' => 13,
                'code' => 'NEBULA',
                'label' => 'Nebula',
                'description' => 'A giant cloud of dust and ionized gases. Nebulae are stellar nurseries where new stars are born. Rich in primordial matter and exotic particles.',
                'domain' => 'Universe',
                'category' => 'anomaly',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => false,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 4,
                'icon' => 'nebula',
                'color' => '#FF69B4',
                'produces_minerals' => ['H2O', 'C', 'DMC', 'AM', 'EM', 'ZPE', 'PE'],
            ],
            [
                'id' => 1,
                'code' => 'ANOMALY',
                'label' => 'Anomaly',
                'description' => 'An unexplained spatial phenomenon. Could be a wormhole, dimensional rift, or unknown alien technology. Highly unpredictable but potentially rewarding.',
                'domain' => 'Universe',
                'category' => 'anomaly',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => false,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 8,
                'icon' => 'anomaly',
                'color' => '#9400D3',
                'produces_minerals' => ['Rh', 'Ir', 'Os', 'Pd', 'AM', 'DMC', 'CP', 'EM', 'QF', 'PE'],
            ],
            [
                'id' => 6,
                'code' => 'COMET',
                'label' => 'Comet',
                'description' => 'An icy small body that releases gas and dust when near a star. Contains frozen volatiles and primordial solar system materials.',
                'domain' => 'Universe',
                'category' => 'debris',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => false,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 2,
                'icon' => 'comet',
                'color' => '#87CEEB',
                'produces_minerals' => ['H2O', 'C', 'SiO2'],
            ],
            [
                'id' => 16,
                'code' => 'ROGUE_PLANET',
                'label' => 'Rogue Planet',
                'description' => 'A planetary-mass object that does not orbit a star. Wandering alone through interstellar space, these worlds are cold and dark but may contain valuable resources.',
                'domain' => 'Universe',
                'category' => 'planet',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => false,
                'is_dockable' => true,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 3,
                'icon' => 'rogue-planet',
                'color' => '#4a4a4a',
                'produces_minerals' => ['Fe', 'Ti', 'Ni', 'Al', 'Cu', 'C', 'SiO2', 'Pt', 'Au', 'Co', 'Li'],
            ],
            [
                'id' => 21,
                'code' => 'EMPTY_SPACE',
                'label' => 'Empty Space',
                'description' => 'A region of space with no significant celestial bodies. Useful for navigation waypoints or hidden rendezvous.',
                'domain' => 'Universe',
                'category' => 'void',
                'is_habitable' => false,
                'is_mineable' => false,
                'is_orbital' => false,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 0,
                'icon' => 'empty',
                'color' => '#000000',
                'produces_minerals' => [],
            ],
            [
                'id' => 22,
                'code' => 'DERELICT',
                'label' => 'Derelict Vessel',
                'description' => 'An abandoned spacecraft drifting in space. May contain salvageable technology, cargo, or clues to its fate. Approach with caution.',
                'domain' => 'Universe',
                'category' => 'debris',
                'is_habitable' => false,
                'is_mineable' => false,
                'is_orbital' => false,
                'is_dockable' => true,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 5,
                'icon' => 'derelict',
                'color' => '#8B4513',
                'produces_minerals' => [],
            ],

            // ============================================================
            // PLANETARY BODIES (System domain)
            // ============================================================
            [
                'id' => 15,
                'code' => 'PLANET',
                'label' => 'Planet',
                'description' => 'A celestial body orbiting a star, massive enough to be rounded by its own gravity. Generic planetary body with varied composition.',
                'domain' => 'System',
                'category' => 'planet',
                'is_habitable' => true,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => true,
                'can_have_trading_hub' => true,
                'can_have_warp_gate' => false,
                'base_danger_level' => 1,
                'icon' => 'planet',
                'color' => '#228B22',
                'produces_minerals' => ['Fe', 'Ti', 'Ni', 'Al', 'Cu', 'C', 'SiO2', 'Pt', 'Au', 'Co', 'Li'],
            ],
            [
                'id' => 20,
                'code' => 'TERRESTRIAL',
                'label' => 'Terrestrial Planet',
                'description' => 'A rocky planet similar to Earth, with a solid surface and potential for habitation. Prime real estate for colonization.',
                'domain' => 'System',
                'category' => 'planet',
                'is_habitable' => true,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => true,
                'can_have_trading_hub' => true,
                'can_have_warp_gate' => false,
                'base_danger_level' => 0,
                'icon' => 'terrestrial',
                'color' => '#32CD32',
                'produces_minerals' => ['Fe', 'Ti', 'Ni', 'Al', 'Cu', 'C', 'SiO2', 'Pt', 'Au', 'Co', 'Li'],
            ],
            [
                'id' => 18,
                'code' => 'SUPER_EARTH',
                'label' => 'Super Earth',
                'description' => 'A terrestrial planet significantly larger than Earth. Higher gravity but rich in resources and potentially habitable.',
                'domain' => 'System',
                'category' => 'planet',
                'is_habitable' => true,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => true,
                'can_have_trading_hub' => true,
                'can_have_warp_gate' => false,
                'base_danger_level' => 1,
                'icon' => 'super-earth',
                'color' => '#2E8B57',
                'produces_minerals' => ['Fe', 'Ti', 'Ni', 'Al', 'Cu', 'C', 'SiO2', 'Pt', 'Au', 'Co', 'Li'],
            ],
            [
                'id' => 14,
                'code' => 'OCEAN',
                'label' => 'Ocean World',
                'description' => 'A planet covered entirely or mostly by liquid water. Rich in aquatic resources and water ice for fuel production.',
                'domain' => 'System',
                'category' => 'planet',
                'is_habitable' => true,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => true,
                'can_have_trading_hub' => true,
                'can_have_warp_gate' => false,
                'base_danger_level' => 1,
                'icon' => 'ocean',
                'color' => '#1E90FF',
                'produces_minerals' => ['H2O', 'Li', 'SiO2', 'C'],
            ],
            [
                'id' => 11,
                'code' => 'LAVA',
                'label' => 'Lava World',
                'description' => 'A volcanic planet with a surface covered in molten rock. Extremely hostile but rich in high-temperature metals and rare elements.',
                'domain' => 'System',
                'category' => 'planet',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 7,
                'icon' => 'lava',
                'color' => '#FF4500',
                'produces_minerals' => ['Fe', 'Ti', 'Ni', 'Au', 'Pt', 'Ir', 'Os', 'Rh'],
            ],
            [
                'id' => 5,
                'code' => 'CHTHONIC',
                'label' => 'Chthonic Planet',
                'description' => 'The exposed core of a former gas giant that lost its atmosphere. Extremely dense with concentrated heavy metals.',
                'domain' => 'System',
                'category' => 'planet',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 6,
                'icon' => 'chthonic',
                'color' => '#8B0000',
                'produces_minerals' => ['Fe', 'Ti', 'Ni', 'Au', 'Pt', 'Ir', 'Os', 'Rh'],
            ],
            [
                'id' => 7,
                'code' => 'DWARF_PLANET',
                'label' => 'Dwarf Planet',
                'description' => 'A small planetary body that orbits the sun but has not cleared its orbital neighborhood. Smaller deposits but easier to mine.',
                'domain' => 'System',
                'category' => 'planet',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => true,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 0,
                'icon' => 'dwarf-planet',
                'color' => '#A0522D',
                'produces_minerals' => ['Fe', 'Ti', 'Ni', 'Al', 'Cu', 'C', 'SiO2', 'Pt', 'Au', 'Co', 'Li'],
            ],

            // ============================================================
            // GAS GIANTS (System domain)
            // ============================================================
            [
                'id' => 8,
                'code' => 'GAS_GIANT',
                'label' => 'Gas Giant',
                'description' => 'A massive planet composed primarily of hydrogen and helium. No solid surface but its atmosphere contains valuable gases and rare materials.',
                'domain' => 'System',
                'category' => 'giant',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 4,
                'icon' => 'gas-giant',
                'color' => '#DAA520',
                'produces_minerals' => ['T', 'C', 'AM'],
            ],
            [
                'id' => 9,
                'code' => 'HOT_JUPITER',
                'label' => 'Hot Jupiter',
                'description' => 'A gas giant orbiting very close to its star. Extreme temperatures but rich in exotic atmospheric compounds.',
                'domain' => 'System',
                'category' => 'giant',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 6,
                'icon' => 'hot-jupiter',
                'color' => '#FF6347',
                'produces_minerals' => ['T', 'C', 'AM'],
            ],
            [
                'id' => 10,
                'code' => 'ICE_GIANT',
                'label' => 'Ice Giant',
                'description' => 'A giant planet composed mainly of elements heavier than hydrogen and helium, such as oxygen, carbon, nitrogen, and sulfur. Contains frozen volatiles.',
                'domain' => 'System',
                'category' => 'giant',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 3,
                'icon' => 'ice-giant',
                'color' => '#00CED1',
                'produces_minerals' => ['H2O', 'C', 'AM', 'DMC'],
            ],

            // ============================================================
            // SMALL BODIES (System domain)
            // ============================================================
            [
                'id' => 12,
                'code' => 'MOON',
                'label' => 'Moon',
                'description' => 'A natural satellite orbiting a planet. Often rich in metals and easier to mine due to low gravity.',
                'domain' => 'System',
                'category' => 'moon',
                'is_habitable' => true,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => true,
                'can_have_trading_hub' => true,
                'can_have_warp_gate' => false,
                'base_danger_level' => 0,
                'icon' => 'moon',
                'color' => '#C0C0C0',
                'produces_minerals' => ['Fe', 'Ti', 'Ni', 'Al', 'SiO2', 'H2O'],
            ],
            [
                'id' => 2,
                'code' => 'ASTEROID',
                'label' => 'Asteroid',
                'description' => 'A small rocky body orbiting the sun. Asteroids are excellent sources of metals and are easy to mine.',
                'domain' => 'System',
                'category' => 'debris',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => true,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 1,
                'icon' => 'asteroid',
                'color' => '#808080',
                'produces_minerals' => ['Fe', 'Ni', 'Pt', 'Au', 'Pd', 'Ir', 'Os', 'Rh', 'Co'],
            ],
            [
                'id' => 3,
                'code' => 'ASTEROID_BELT',
                'label' => 'Asteroid Belt',
                'description' => 'A region of space containing a high concentration of asteroids. Rich mining grounds but navigation requires care.',
                'domain' => 'System',
                'category' => 'debris',
                'is_habitable' => false,
                'is_mineable' => true,
                'is_orbital' => true,
                'is_dockable' => false,
                'can_have_trading_hub' => false,
                'can_have_warp_gate' => false,
                'base_danger_level' => 2,
                'icon' => 'asteroid-belt',
                'color' => '#696969',
                'produces_minerals' => ['Fe', 'Ni', 'Pt', 'Au', 'Pd', 'Ir', 'Os', 'Rh', 'Co'],
            ],
        ];
    }
}
